[package]
name = "advent_of_code_19"
version = "0.1.0"
authors = ["oshenton"]
edition = "2018"

[[bin]]
name = "advent_of_code_19"
src = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]